### PR TITLE
add extrapolate factors

### PR DESCRIPTION
**Pull request by micaelverissimo**
The main modifications are:

1. Add a extrapolate factor to the linear fit, now we can define an $\epsilon$ that can improve more the detection w.r.t to the detection;
2. Force the flag to allow gpu (if have) to grow.
3. Fix the index problem in crossval table when is filled with two or more train_tags.

### CODE REVIEW

**Review by gabriel-milan — APPROVED** [review]
Just please bump version on `setup.py` before you merge

**Comment by micaelverissimo** [comment]
Version updated!

**Comment by gabriel-milan** [comment]
Nice. All good to me :)

**Comment by micaelverissimo** [comment]
@gabriel-milan everything is ok? Can merge?

**Pull request merged**
